### ISSUE TITLE
Present each participant with different stimuli

### ISSUE THREAD

**Issue by adamliter** [presleyp/Speriment#56]
Hi @presleyp, I have a question about whether it's possible to present each participant in the same experiment with different stimuli using Speriment.

I'm not sure that I entirely understand how `SampleFrom()` works, but, to the extent that I do understand it, it seems like `SampleFrom()` presents each participant with the same stimuli but just in a different order. Is this correct?

In any event, I've created a mockup of the experiment that I'm currently trying to design. Perhaps you could help offer insight as to whether there is a good way to present each participant with different stimuli in Speriment.

The following mokcup has defined a function (`MakeExperimentStimuli()`) that returns a random list of training stimuli and a random list of testing stimuli based on setting a random seed.

In this mockup (not the actual experiment that we're trying to implement, but close enough), participants are given some letters and told whether or not they are lower or upper case. That's the training phase.

In the testing phase, they're given some letters and asked whether the letter is upper or lower case.

The goal is to be able to set a different value for ListNum in the call to `MakeExperimentStimuli()` for each participant in the experiment.

Based on my understanding of Speriment, it seems like there isn't currently a good way of doing this. However, if you have thoughts on a workaround or whether this is possible to implement, I would greatly appreciate it.

The one possible workaround that has occurred to me is trying to create a bank by iterating over possible list numbers for `MakeExperimentStimuli()` and then sampling from that bank on a per-participant basis, but I'm not sure that I really understand `SampleFrom()` and whether this would actually work.

But something like the following?:

```python
def MakeExperimentBank(NumOfLists):
    TempList = []
    for n in range(1,NumOfLists+1):
        TempDict = {}
        TempDict.update({'ListNum': n})
        TempDict.update({'TrainingStimuli': MakeExperimentStimuli(n,6,6)['TrainingStimuli']})
        TempDict.update({'TestingStimuli': MakeExperimentStimuli(n,6,6)['TestingStimuli']})
        TempList.append(TempDict)
    return TempList

bank = MakeExperimentBank(100)
```

Another possible workaround that has occurred to me but that I'm again not sure how to implement would be to somehow make use of PsiTurk's `num_conds` or `num_counters` variables.

Anywhere, here's the mockup code. If you have any thoughts or suggestions, I'd really appreciate it. Thanks again for an awesome tool! :+1: :smile_cat: 

## my_fake_experiment.py
```python
from speriment import *

introduction = '''Thanks for your participation in this experiment. In this experiment, you will learn about lower and upper case letters.
<br><br>
After being exposed to some letters, you will be tested on what you have learned.'''

testing_instructions = '''Now that you have learned a little bit about lower and upper case letters, it is time to test what you have learned. Your job is to indicate whether the letter you see is lower or upper case.
<br><br>
If the letter is lower case, choose "lower". If the letter is upper case, choose "upper".'''

testing_question = '''Is the following letter lower or upper case?<br><br>'''

goodbye = '''Thank you for participating in this experiment! Make sure to click the Complete HIT button on the next page.'''

with make_experiment(IDGenerator()):
    
    # Function to create stimuli
    # The stimuli are pseudorandomized based on ListNum
    def MakeExperimentStimuli(ListNum, TrainingN, TestingN):
        '''
        Takes three ints: ListNum, TrainingN, and TestingN
        
        ListNum sets a random seed
        TrainingN is the number of training items (must be > 0 )
        TestingN is the number of testing items (must be > 0 )
        
        Returns a dictionary with two things (the values of which are themselves lists of dictionaries):
        
        (i) TrainingStimuli
        (ii) TestingStimuli
        '''
        
        import string
        import random
        
        ################################################
        # Helper functions                             #
        ################################################
        def GetPossibleStimuli(ListOfPossibleStimuli):
            '''
            Takes a string (intended to be all the lower and upper case letters)
            
            Returns a list of dictionaries with two key-value pairs ('STIMULUS' and 'TYPE')
            for each possible stimulus in ListOfPossibleStimuli
            '''
            
            TempList = []
            for letter in ListOfPossibleStimuli:
                
                if letter.islower():
                    Type = 'lower'
                else:
                    Type = 'upper'
                
                TempDict = {}
                TempDict.update({'STIMULUS': letter})
                TempDict.update({'TYPE': Type})
                TempList.append(TempDict)
            
            return TempList
            
        def MutateStimuli(ListOfStimuli, GeneralType):
            '''
            Takes a list of dictionaries (ListOfStimuli) and a string (GeneralType)
            
            Returns an updated list of dictionaries with two new key-value pairs (TYPE and GENERAL_TYPE)
            '''
            # Update the dictionaries in the list of stimuli
            for dict in ListOfStimuli:
                dict.update({'GENERAL_TYPE': GeneralType})
                
            return ListOfStimuli
        
        PossibleStimuli = list(GetPossibleStimuli(string.ascii_lowercase + string.ascii_uppercase))
        
        random.seed(ListNum * 123)
        
        TrainingStimuli = random.sample(PossibleStimuli, TrainingN)
        TrainingStimuli = MutateStimuli(TrainingStimuli, 'Training')
        
        TestingStimuli = random.sample(PossibleStimuli, TestingN)
        TestingStimuli = MutateStimuli(TestingStimuli, 'Testing')
        
        return {'TrainingStimuli': TrainingStimuli, 'TestingStimuli': TestingStimuli}
    
    TAGS = ['STIMULUS', 'TYPE', 'GENERAL_TYPE']
    
    training_pages = [Page(
                           ['''The following letter is ''' + str(row['TYPE']) + ''' case.<br><br>''',
                           row['STIMULUS']],
                           tags = {tag: row[tag] for tag in TAGS}
                           ) for row in MakeExperimentStimuli(1,6,6)['TrainingStimuli']]
    
    testing_pages = [Page(
                          [testing_question,
                          row['STIMULUS']],
                          options = [Option("lower"), Option("upper")],
                          tags = {tag: row[tag] for tag in TAGS},
                          keyboard = False
                          ) for row in MakeExperimentStimuli(1,6,6)['TestingStimuli']]
                          
    intro_instructions_block = Block(pages = [
        Page(introduction,
             tags = {'GENERAL_TYPE': 'Instructions'})])
    
    testing_instructions_block = Block(pages = [
        Page(testing_instructions,
             tags = {'GENERAL_TYPE': 'Instructions'})])
    
    training_block = Block(pages = training_pages)

    testing_block = Block(pages = testing_pages)
    
    thanks_block = Block(pages = [Page(
                                       goodbye,
                                       tags = {'GENERAL_TYPE': 'Instructions'}
                                       )])
                                       
    experiment = Experiment([intro_instructions_block,
                             training_block,
                             testing_instructions_block,
                             testing_block,
                             thanks_block])
    
    experiment.install('MyFakeExp')
```

**Comment by presleyp** [comment]
Yeah, I wish there were some standard terminology for this sort of thing; it's hard to know how to discuss it. Here's the new documentation for SampleFrom (if you see Items, that's a construct I'm going to add in the release after the release with the resource options): https://github.com/presleyp/Speriment/blob/item/doc/feature_examples.md#recombine-components-on-the-fly. Does that help at all?

**Comment by adamliter** [comment]
Thanks for the quick response, @presleyp! I'm not sure how I originally missed that document with that explanation. It's definitely helpful for better understanding what `SampleFrom()` does. However, I'm not sure that I'm able to accomplish what I'd like to with `SampleFrom()` now that I better understand it.

At the end of this is a naive implementation of the mockup experiment that doesn't work.

The relevant part is this:

```python
    training_pages = [Page(
                           ['''The following letter is ''' + str(row['TYPE']) + ''' case.<br><br>''',
                           row['STIMULUS']],
                           tags = {tag: row[tag] for tag in TAGS}
                           ) for row in SampleFrom('experiment_bank', field = 'TrainingStimuli')]
    training_block = Block(pages = training_pages, banks = experiment_bank)
```

This returns `TypeError: iteration over non-sequence`. So I take it that `SampleFrom()` is outsourcing the per-participant randomization to the compiled-down JavaScript? Or something like that?

My `experiment_bank` is a list of dictionaries. The value of the item in the dictionary whose key is `TrainingStimuli` is itself a list of dictionaries that I was hoping to be able to iterate over in creating a `Page()`.

I'll try to think about if there is a better way to do what I'm trying to accomplish given how (I think) `SampleFrom()` works, but if you have any thoughts or suggestions, I'd greatly appreciate it!

## my_fake_experimeny.py
```python
from speriment import *

introduction = '''Thanks for your participation in this experiment. In this experiment, you will learn about lower and upper case letters.
<br><br>
After being exposed to some letters, you will be tested on what you have learned.'''

testing_instructions = '''Now that you have learned a little bit about lower and upper case letters, it is time to test what you have learned. Your job is to indicate whether the letter you see is lower or upper case.
<br><br>
If the letter is lower case, choose "lower". If the letter is upper case, choose "upper".'''

testing_question = '''Is the following letter lower or upper case?<br><br>'''

goodbye = '''Thank you for participating in this experiment! Make sure to click the Complete HIT button on the next page.'''

with make_experiment(IDGenerator()):
    
    # Function to create stimuli
    # The stimuli are pseudorandomized based on ListNum
    def MakeExperimentStimuli(ListNum, TrainingN, TestingN):
        '''
        Takes three ints: ListNum, TrainingN, and TestingN
        
        ListNum sets a random seed
        TrainingN is the number of training items (must be > 0 )
        TestingN is the number of testing items (must be > 0 )
        
        Returns a dictionary with two things (the values of which are themselves lists of dictionaries):
        
        (i) TrainingStimuli
        (ii) TestingStimuli
        '''
        
        import string
        import random
        
        ################################################
        # Helper functions                             #
        ################################################
        def GetPossibleStimuli(ListOfPossibleStimuli):
            '''
            Takes a string (intended to be all the lower and upper case letters)
            
            Returns a list of dictionaries with two key-value pairs ('STIMULUS' and 'TYPE')
            for each possible stimulus in ListOfPossibleStimuli
            '''
            
            TempList = []
            for letter in ListOfPossibleStimuli:
                
                if letter.islower():
                    Type = 'lower'
                else:
                    Type = 'upper'
                
                TempDict = {}
                TempDict.update({'STIMULUS': letter})
                TempDict.update({'TYPE': Type})
                TempList.append(TempDict)
            
            return TempList
            
        def MutateStimuli(ListOfStimuli, GeneralType):
            '''
            Takes a list of dictionaries (ListOfStimuli) and a string (GeneralType)
            
            Returns an updated list of dictionaries with two new key-value pairs (TYPE and GENERAL_TYPE)
            '''
            # Update the dictionaries in the list of stimuli
            for dict in ListOfStimuli:
                dict.update({'GENERAL_TYPE': GeneralType})
                
            return ListOfStimuli
        
        PossibleStimuli = list(GetPossibleStimuli(string.ascii_lowercase + string.ascii_uppercase))
        
        random.seed(ListNum * 123)
        
        TrainingStimuli = random.sample(PossibleStimuli, TrainingN)
        TrainingStimuli = MutateStimuli(TrainingStimuli, 'Training')
        
        TestingStimuli = random.sample(PossibleStimuli, TestingN)
        TestingStimuli = MutateStimuli(TestingStimuli, 'Testing')
        
        return {'TrainingStimuli': TrainingStimuli, 'TestingStimuli': TestingStimuli}
    
    def MakeExperimentBank(NumOfLists):
        '''
        Takes an int (NumOfLists); must be > 0
        
        Returns a list of dictionaries with three key-value pairs:
        
        (i) The ListNum used in the call to MakeExperimentStimuli
        (ii) The TrainingStimuli (this is a list of dictionaries)
        (iii) The TestingStimuli (this is a list of dictionaries)
        '''
        TempList = []
        for n in range(1,NumOfLists+1):
            TempDict = {}
            TempDict.update({'ListNum': n})
            TempDict.update({'TrainingStimuli': MakeExperimentStimuli(n,1,1)['TrainingStimuli']})
            TempDict.update({'TestingStimuli': MakeExperimentStimuli(n,1,1)['TestingStimuli']})
            TempList.append(TempDict)
        return TempList
    
    experiment_bank = MakeExperimentBank(100)
    
    TAGS = ['STIMULUS', 'TYPE', 'GENERAL_TYPE']
    
    training_pages = [Page(
                           ['''The following letter is ''' + str(row['TYPE']) + ''' case.<br><br>''',
                           row['STIMULUS']],
                           tags = {tag: row[tag] for tag in TAGS}
                           ) for row in SampleFrom('experiment_bank', field = 'TrainingStimuli')]
    training_block = Block(pages = training_pages, banks = experiment_bank)
    
    testing_pages = [Page(
                          [testing_question,
                          row['STIMULUS']],
                          options = [Option("lower"), Option("upper")],
                          tags = {tag: row[tag] for tag in TAGS},
                          keyboard = False
                          ) for row in SampleFrom('experiment_bank', field = 'TestingStimuli')]
    testing_block = Block(pages = testing_pages, banks = experiment_bank)
                          
    intro_instructions_block = Block(pages = [
        Page(introduction,
             tags = {'GENERAL_TYPE': 'Instructions'})])
    
    testing_instructions_block = Block(pages = [
        Page(testing_instructions,
             tags = {'GENERAL_TYPE': 'Instructions'})])
    
    thanks_block = Block(pages = [Page(
                                       goodbye,
                                       tags = {'GENERAL_TYPE': 'Instructions'}
                                       )])
                                       
    experiment = Experiment([intro_instructions_block,
                             training_block,
                             testing_instructions_block,
                             testing_block,
                             thanks_block])
    
    experiment.install('MyFakeExp')
```

**Comment by presleyp** [comment]
You weren't just missing it - it's not in master yet. 

Yes, `SampleFrom` is a flag that says "pick one at JavaScript runtime." You can write a function to pick randomly at Python runtime using all the power of Python, but it will pick right now and output a JSON file and that JSON file won't change across participants.

Can you describe the situation you want to create, like "each participant should see..."?

**Comment by adamliter** [comment]
So in the mockup I gave you, there's a list of all possible stimuli. Each participant should see a proper subset of all of the possible stimuli, but the proper subset should not be the same for each participant. In other words, I want to randomly choose two proper subsets from the list of all possible stimuli for each participant: (i) a training set, and (ii) a testing set.

The real use case is slightly more complicated than the mockup above in that the list of testing stimuli depend on the list of training stimuli. So in the real use case, I need some way of keeping track of the training stimuli that a participant saw so that I can choose the testing stimuli on the basis of the training stimuli.

**Comment by adamliter** [comment]
Based on the fact that it seems easiest to do the randomization at Python runtime, it seems like the easiest thing to do would be to generate say 100 pairs of training and testing sets and then assign a different list to each participant at experiment runtime. This is what my attempt above was trying to do.

I had created an experiment bank that looks something like this:

```python
experiment_bank = [{ListNum: 1, TrainingStimuli: [{'STIMULUS': foo, TYPE: 'Training'}], TestingStimuli: [{'STIMULUS': bar, TYPE: 'Training'}]},
{ListNum: 2, TrainingStimuli: [{'STIMULUS': baz, TYPE: 'Training'}], TestingStimuli: [{'STIMULUS': qux, TYPE: 'Training'}]}]
```
I was trying to use `SampleFrom()` to get one of the dictionaries from inside of the `experiment_bank` for each participant, and then I wanted to iterate over the values of 'TrainingStimuli' and 'TestingStimuli', which are themselves also lists of dictionaries (though in the code above, the list only has one value for the sake of making it semi-readable). This obviously doesn't work since the `SampleFrom()` magic is being outsourced to the JavaScript.

Any thoughts on a better way of doing this?

**Comment by presleyp** [comment]
Ok, so far I think `SampleFrom` can handle this. It sounds like [this case](https://github.com/presleyp/Speriment/blob/item/doc/feature_examples.md#sample-multiple-related-properties) to me. You'd have a bank like:

`experiment_bank = [{'training': 'A', 'testing': 'a'}, {'training': 'B', 'testing': 'b'}]`

And pages like:

`training_page = Page(SampleFrom('experiment_bank', field = 'training', variable = 1))`
`testing_page = Page(SampleFrom('experiment_bank', field = 'testing', variable = 1))`

That would mean that if `training_page` shows A, `testing_page` shows a; otherwise B and b. If you have more dictionaries in `experiment_bank` than training pages, then you will sample a proper subset of training materials for each participant. The contents of the proper subset will vary randomly across participants. With the options given here, it won't sample the same training text more than once.

It's also possible to make lists and choose them on a per-participant basis, if you'd rather do that, but I don't know if you'd get performance issues if you had a huge amount of pregenerated material.

**Comment by adamliter** [comment]
Hmm, I'll have to think about this a little bit more. I'm about to jump on a plane in a couple of seconds.

But I'm not sure that this will work for the ultimate use case. The testing stimuli depend on the totality of the training stimuli. And there are also different numbers of training stimuli from testing stimuli.

For example, say there are 600 possible stimuli. From these possible 600 stimuli, I randomly choose 200 training stimuli and 60 testing stimuli for a participant. I need to know the 200 testing stimuli because I then want 10 of the 60 testing stimuli to be stimuli that occurred during training.

Anyway, jumping on a plane ...

Thanks again, @presleyp! :smile:

**Comment by presleyp** [comment]
So you'd make 200 training pages, each one sampling with the field `training` and variables 1-200, and 60 testing pages, each one sampling with the field `testing` and variables 1-10 and 201-251. Then ten of the testing pages would be the same as training pages, and 50 would be different. Because variables don't get meaning until runtime and page order is randomized, I don't think there would be any weird correlations unless you have multiple training blocks or multiple testing blocks. If you have one training and one testing block, it would be ok.

**Comment by adamliter** [comment]
@presleyp Wouldn't your last suggestion result in the participants seeing the same stimuli, albeit it in different orders? Or am I still misunderstanding how `SampleFrom()` works?

**Comment by presleyp** [comment]
SampleFrom randomly samples from a bank of stimuli. The way it manages to be random is that the bank is shuffled once for each participant. Variables get turned into indices, so whether you give it variable 1 or 'broccoli', the first variable in the experiment for a given bank becomes 0 and takes the first thing from that now-shuffled bank. So there is no correlation between one participant's first sample and the next participant's first sample; they're neither guaranteed to be the same nor guaranteed to be different. If you have a very large bank and don't sample from it that many times, they're more likely to be different. If you need them to definitely be different across participants, you need to use latin squares or treatments.

Your example isn't working because you didn't put your page in a list. I should add validation for that, it's a common mistake. The rest looks right and should do what you expect.

In order to think about how to do something with SampleFrom, don't think about randomly sampling and *then* making choices based on what happened. Think about for each thing you could sample, what it would entail for the rest of the experiment; put differently, think about groups that travel together. If there's a deterministic mapping from what you train on to what you test on, your case sounds doable using fields. If what you train on merely limits the pool you want to randomly sample from in testing, then SampleFrom can't do it elegantly. You could in principle make lots of banks - the bank of words that doesn't have these consonants in it, etc, but at that point your approach sounds easier.

**Comment by adamliter** [comment]
Ah, thanks! I'm not sure how I missed that regarding the small test with `SampleFrom()`. (As an aside, however, the `sampling_block` in the current implementation of [`example.py`](https://github.com/presleyp/Speriment/blob/master/doc/example.py) also displays nothing for me, despite the fact that that page is in a list. Based on the code, I would expect it to display either 'sampled1' or 'sampled2'. Perhaps my expectations are wrong.)

At any rate, thanks for the further explanation of `SampleFrom()`! That really helps. It is indeed the case for our experiment that the training stimuli merely limit the possible testing stimuli; there's no deterministic mapping.

So I did go ahead and implement this using `treatments` and `num_counters`. With 100 different blocks of training and testing stimuli and with setting `num_counters` to 100, there's only a second or so delay when starting the experiment, at least when it's running locally. I have yet to test in a sandbox on AMT, but I don't think that delay is too bad if it holds up in a sandbox on AMT.

If it gets any worse, we could just set `num_counters` to 25, or something, and then run 4 separate versions of the experiment.

Thanks again for all your help, @presleyp! :smiley_cat: And sorry for bugging you so much with all of these questions! :stuck_out_tongue_closed_eyes:

**Comment by presleyp** [comment]
No problem! There may well be problems in example.py (in master) - I can't wait to get some changes merged to make the docs better. I'm really close on merging in the resource changes.

**Comment by adamliter** [comment]
Sounds good. Thanks, @presleyp!

**Comment by presleyp** [comment]
Summary for future reference: `SampleFrom` cannot merely limit the pool from which to randomly sample based on which items were previously randomly sampled.

**Comment by adamliter** [comment]
Thanks @presleyp. That's a helpful summary. :smile:
