### ISSUE TITLE
SampleFrom breaks if you check JSON

### ISSUE THREAD

**Issue by presleyp** [presleyp/Speriment#57]
This is on the Python side but affects the experiment online. The magic that makes SampleFrom variables work gets messed up if you call the `to_JSON` method more than once. It gets called in `install` and `to_file`.

**Comment by presleyp** [comment]
@adamliter this is why your SampleFroms were blank the other day. How are you on time? I'd like to fix this but I can release the resource timing stuff if you need it. So far I just have the bare minimum - autoplay and the ability to hide controls. It doesn't stop you from choosing an option or clicking Next.

**Comment by adamliter** [comment]
Thanks @presleyp! :smile: I think my collaborator and I would ideally like to run the experiment by the end of the month. We also would like to have the functionality where we can prevent a participant from choosing a response or clicking next before the sound file has finished playing. I'm not sure if implementing that before the month is over is doable for you. If so, then you might as well wait. However, if you don't think that's doable, then maybe a release would be useful for us?

Anyway, thanks again for all your help and for Speriment! :smile_cat:
