### ISSUE TITLE
Add options for resource interaction.

### ISSUE THREAD

**Issue by presleyp** [presleyp/Speriment#7]
Only play sound once, play sound on page load, disable selections until sound is done playing, etc.

**Comment by adamliter** [comment]
I was poking around the issues section, and it looks like you've already created an issue for this! :smile: 

It would be really useful for the experiment that I'm currently designing if it were possible to play a sound when the page is loaded. It would be even more ideal if it were possible to set a time delay and have the sound played after the page loads according to that time delay. And it would be super ideal if it were possible to disable the selections until the sound is done playing.

Any idea what the timeline might be like for implementing these features? Thanks! :+1:

**Comment by adamliter** [comment]
^^^ Also, I hope the above doesn't come across as rude or pushy. :smile_cat: I wish I knew more about Python and JavaScript so that I could help implement these features, but I unfortunately don't know a ton about either of the programming languages at the moment, so I don't think I'd be much help.

I definitely appreciate all you've done in making Speriment open source. It's a great project, so thanks for a great tool! :smile:

**Comment by presleyp** [comment]
No worries! Work lets me spend 8 hours a week on this so I should be able to get at least some of this done this week.

**Comment by adamliter** [comment]
That'd be awesome. Thanks, Presley. My collaborator and I would be forever grateful! :smile:

**Comment by presleyp** [comment]
@adamliter, I wrote the code to allow autoplay and to remove controls (those were the simplest changes to make), but it looks like somehow my Python code is broken (probably a version issue, but it's something I should fix anyway and had already started on). So this will take a little bit longer while I clean all of that up.

**Comment by adamliter** [comment]
Thanks for the update on things, @presleyp! I really appreciate it. Thanks again for a great project and tool. :smile_cat:

**Comment by presleyp** [comment]
@adamliter, the branch resource-timing passes my tests, but I should really test it manually before merging it into master and making a new release. If you have time to try, you could install from that branch and try it out yourself; I just don't want to put it on npm and pip until I've poked around, and it might take me a few days to get to that.

**Comment by adamliter** [comment]
@presleyp Thanks for this! It might also take me a few days before I can test things out, but I'll try to test things as soon as I can. I still need to prepare for teaching tomorrow, and I have some grading and other miscellaneous tasks that need to be finished in the next couple of days, but I'll test this as soon as I can. Again, this is much appreciated. Thanks for Speriment! :smile:

**Comment by adamliter** [comment]
Hi @presleyp, sorry that I'm just now getting around to testing things out. It's been a hectic week or two with a lot of grading and a conference. Anyway, I'm wondering if there's a good way to install the development versions in `resource-timing` so that I can test them.

For the Python part, I tried doing `pip install git+https://github.com/presleyp/Speriment.git@resource-timing`, but this returned:

```
Collecting git+https://github.com/presleyp/Speriment.git@resource-timing
  Cloning https://github.com/presleyp/Speriment.git (to resource-timing) to /var/folders/t7/q37prlc90yd3wql38h4gnkrw0000gn/T/pip-wcFg0b-build
  Requirement already satisfied (use --upgrade to upgrade): speriment==0.7.0 from git+https://github.com/presleyp/Speriment.git@resource-timing in /Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): jsonschema in /Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages (from speriment==0.7.0)
Requirement already satisfied (use --upgrade to upgrade): functools32 in /Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages (from jsonschema->speriment==0.7.0)
```

So I then tried `pip install --upgrade git+https://github.com/presleyp/Speriment.git@resource-timing` which seems to have worked (it at least reinstalled Speriment). However, now when I try to run `python my_experiment.py`, I get:

```
Traceback (most recent call last):
  File "VSH_Exp4_OnlineExp.py", line 8, in <module>
    from speriment import *
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/speriment/__init__.py", line 1, in <module>
    from components import *
ImportError: No module named components
```
Any suggestions for install the Node.js development branch would also be really helpful, as I'm really not familiar with Node.

Is it best to just clone the repo and manually copy files into place for the time being?

Thanks again! :smile:

**Comment by presleyp** [comment]
Hey, I started testing it and there are some problems. It'll be a lot easier for you to just download the released version so I'll let you know once I have it fixed and uploaded.

**Comment by adamliter** [comment]
Sounds good, @presleyp! Thanks for the quick response. :smiley_cat:

**Comment by presleyp** [comment]
fyi since I don't have the good docs merged yet: Resource wraps the filename and takes the optional arguments autoplay, controls (if false autoplay will be true because otherwise there's no way to play), and required (disables Next and options till done - if you use this turning controls off is recommended bc otherwise you can skip forward). So like:

`resources = [Resource('static/audio/sounds.mp3', controls = False, required = True)]`

**Comment by adamliter** [comment]
Thanks for the info, @presleyp! :smile: Will these changes be pushed to PyPI and `npm` at some point so it's easy to install the updated versions?

**Comment by presleyp** [comment]
Yeah, very soon.

**Comment by adamliter** [comment]
Sounds good, thanks! :+1:

**Comment by presleyp** [comment]
Done!

**Comment by adamliter** [comment]
@presleyp I'm not sure if I installed things incorrectly, or is it possible that the `components` folder didn't make it into the release on PyPI? Trying to run my experiment script returns:

```
Traceback (most recent call last):
  File "VSH_Exp4_OnlineExp.py", line 8, in <module>
    from speriment import *
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/speriment/__init__.py", line 1, in <module>
    from components import *
ImportError: No module named components
```

Looking inside of my virtual environment, I see:

```
lib/python2.7/site-packages/speriment
├── __init__.py
├── __init__.pyc
├── compiler.py
├── compiler.pyc
├── utils.py
└── utils.pyc
```

Whereas when I downgrade back to 0.7.0, I see:

```
lib/python2.7/site-packages/speriment
├── __init__.py
├── __init__.pyc
├── compiler.py
├── compiler.pyc
├── components.py
├── components.pyc
├── sperimentschema.json
├── utils.py
└── utils.pyc
```

**Comment by presleyp** [comment]
Ah, components is a package now so maybe I needed to do something different
to get it to upload. I'll take a look.

**Comment by adamliter** [comment]
Sounds good. Thanks! :+1:

**Comment by presleyp** [comment]
Ok, it looks like `components` got uploaded now.

**Comment by adamliter** [comment]
@presleyp Thanks! I'm still having a few problems. It looks like `sperimentschema.json` might still be missing from the upload to PyPI, which I think is causing problems.

When trying to process my experiment with Python, I get:

```
Traceback (most recent call last):
  File "VSH_Exp4_OnlineExp.py", line 494, in <module>
    experiment.install('VSH_Exp4_OnlineExp')
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/speriment/components/experiment.py", line 79, in install
    self.to_file('./static/js/' + filename, varname)
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/speriment/components/experiment.py", line 68, in to_file
    self._validate_json(json_experiment)
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/speriment/components/experiment.py", line 56, in _validate_json
    contents = pkg_resources.resource_string(__name__, 'sperimentschema.json')
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1162, in resource_string
    self, resource_name
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1602, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1725, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/Users/adamliter/.virtualenvs/speriment-test/lib/python2.7/site-packages/speriment/components/sperimentschema.json'
```

**Comment by presleyp** [comment]
Lame, that was an issue I thought of and thought I fixed but apparently didn't. For your immediate purposes, you can probably copy it from Github and drop it in. I'll try to figure out how I'm supposed to describe its location in `setup.py`.

**Comment by adamliter** [comment]
Thanks @presleyp! Copying and pasting it into `/path/to/virtual-environment/lib/python2.7/site-packages/speriment/components` makes everything work.

Thanks again for all of your help and for a great tool! :smile_cat: :+1: My collaborator and I are really grateful.

**Comment by presleyp** [comment]
No problem! Sorry it's been so rocky, I took about 6 months off from this
project and a lot of things changed underneath me!

**Comment by adamliter** [comment]
No worries at all! We're really grateful that you've been so responsive and willing to help. Much appreciated. :smile: Hope you're having a good weekend.
